## YAML Template.
---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TravelInV
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
