## YAML Template.
---
server:
  port: 3100

spring:
  datasource:
    url: jdbc:postgresql://travelinv.postgres.database.azure.com:5432/travelinv
    username: admin_azure
    password: Baitaplonso7
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
