name: Docker build and run images

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: sonuit347/travelinv
      - name: Build Docker image
        run: docker build -t sonuit347/travelinv:latest . 
      - name: Run a Docker image
        run: docker run -p 3100:3100 sonuit347/travelinv:latest
