name: Docker build and run images

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: sonuit347/travelinv
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/travelinvserver:v1.0.0
          
      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/travelinvserver:v1.0.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          
      - name: Configure kubectl
        run: az aks get-credentials --resource-group TravelInVServer --name travelinv --overwrite-existing

      - name: Update Kubernetes deployment
        run: kubectl rollout restart deployment/java-server
